version: "3"
services:
  db:
    image: postgres:13
    container_name: budget-bee-db
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
