version: "3"
services:
  db:
    image: postgres:13
    container_name: budget-bee-dev-db
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data

  api:
    build:
      context: ./
      dockerfile: ./api/Dockerfile.dev
    image: budget-bee-dev-api
    container_name: budget-bee-dev-api
    volumes:
      - ./api:/opt/api
      - /opt/api/node_modules/
    env_file:
      - ./.env
    ports:
      - 3000:3000
    depends_on:
      - db

  app:
    build:
      context: ./
      dockerfile: ./app/Dockerfile.dev
    image: budget-bee-dev-app
    container_name: budget-bee-dev-app
    volumes:
      - ./app:/opt/app
      - /opt/app/node_modules/
    env_file:
      - ./.env
    depends_on:
      - api
    ports:
      - 5173:5173
